# Generated by Django 3.2.6 on 2021-09-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberArtisticDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistic_discipline', models.CharField(choices=[('Dance', 'Dance'), ('Theatre', 'Theatre'), ('Painting', 'Painting'), ('Nothing Selected', 'Nothing Selected')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='artistic_disciplines',
            field=models.ManyToManyField(blank=True, related_name='members', to='accounts.MemberArtisticDiscipline'),
        ),
    ]
