# Generated by Django 3.2.6 on 2021-09-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_memberprofile_public_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='artistic_disciplines',
            field=models.ManyToManyField(null=True, related_name='members', to='accounts.MemberArtisticDiscipline'),
        ),
    ]
