# Generated by Django 3.2.6 on 2021-09-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_memberprofile_artistic_disciplines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='artistic_disciplines',
            field=models.ManyToManyField(blank=True, related_name='members', to='accounts.MemberArtisticDiscipline'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='hashtags',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
