# Generated by Django 3.2.6 on 2021-09-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_memberprofile_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='website',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
