# Generated by Django 3.2.6 on 2021-09-11 04:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210910_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='artistic_disciplines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=90), blank=True, null=True, size=None),
        ),
    ]
